#%RAML 1.0 NamedExample
value:
  - id: 1
    identification_id: 2
    number: 4321
    street: "Wall Street"
    unit: "1A"
    city: "Angeles"
    state: "Pampanga"
    zipcode: "2315"
    type: "Home"
    created: "2021-07-17 14:55:44"
    updated: "2021-07-17 14:55:45"
