#%RAML 1.0 NamedExample
value:
  - id: 1
    identification_id: 2
    value: "ernestpaulferrer@gmail.com"
    preferred: true
    type: "Email"
    created: "2021-07-17 14:55:44"
    updated: "2021-07-17 14:55:45"